[package]
edition = "2021"
name = "rust-node-workers"
version = "0.0.0"

[features]
without-napi = ["napi-derive/noop"]

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
# Default enable napi4 feature, see https://nodejs.org/api/n-api.html#node-api-version-matrix
napi = { version = "2.2.0", default-features = false, features = ["napi4"] }
napi-derive = "2.2.0"
serde_json = "1.0.79"
serde = { version = "1.0.136", features = ["derive"] }

[build-dependencies]
napi-build = "1.2.1"

[profile.release]
lto = true
