/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function doRsTaskFromJsCb(taskCb: (...args: any[]) => any): void
export function doRsTaskFromCmd(): void
export function doRsTaskFromWorkers(): void
